Repository wg-easy/wg-easy, pull requests merged in 2024-07, with the labels that each got.

#1160 Fix a small typo in README.md
  README.md
Labels: documentation

#1161 import & export configuration
  assets/screenshot.png
  src/lib/Server.js
  src/lib/WireGuard.js
  src/www/index.html
  src/www/js/api.js
  src/www/js/app.js
  src/www/js/i18n.js
Labels: enhancement

#1166 refactor: import & export configuration
  assets/screenshot.png
  src/lib/Server.js
  src/lib/WireGuard.js
  src/www/css/app.css
  src/www/index.html
  src/www/js/api.js
  src/www/js/app.js
  src/www/js/i18n.js
Labels: enhancement

#1174 refactor: optimize build config, factorize code, enhance SVG icons
  assets/screenshot.png
  src/lib/WireGuard.js
  src/www/index.html
Labels: enhancement

#1180 feat: PASSWORD_HASH helpers
  Dockerfile
  How_to_generate_an_bcrypt_hash.md
  README.md
  src/config.js
  src/lib/Server.js
  src/wgpw.mjs
  src/wgpw.sh
Labels: documentation, enhancement

#1202 update ipv6 support v2
  src/config.js
  src/lib/WireGuard.js
  src/www/js/api.js
  src/www/js/app.js
Labels: enhancement

#1206 fix: responsive buttons on mobile
  How_to_generate_an_bcrypt_hash.md
  package.json
  src/config.js
  src/package.json
  src/www/css/app.css
  src/www/index.html
Labels: enhancement

#1208 Fix "invalid reference format" in production Docker build
  .github/workflows/deploy.yml
Labels: bug

#1211 prepare: version bump and changelog
  docs/changelog.json
  src/package.json
Labels: documentation

#1229 remove PASSWORD env unused and replace by PASSWORD_HASH
  README.md
  docker-compose.dev.yml
  docker-compose.yml
Labels: documentation
