Repository wg-easy/wg-easy, pull requests merged in 2024-08, with the labels that each got.

#1233 Spelling in How_to_generate_an_bcrypt_hash.md
  How_to_generate_an_bcrypt_hash.md
Labels: documentation

#1236 fixup: docker-compose.dev.yml
  docker-compose.dev.yml
Labels: bug

#1226 Create pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#1238 chore: Update i18n.js Turkish translations
  src/www/js/i18n.js
Labels: enhancement

#1249 Add autocomplete attribute to password input
  src/www/index.html
Labels: bug

#1251 Update i18n.js
  src/www/js/i18n.js
Labels: documentation

#1199 Version 14: Home Assistent support, PASSWORD_HASH (inc. Helper), translation updates, bugfixes and more
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-nightly.yml
  .github/workflows/deploy-pr.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/npm-update-bot.yml
  Dockerfile
  How_to_generate_an_bcrypt_hash.md
  README.md
  assets/screenshot.png
  docker-compose.dev.yml
  docker-compose.yml
  docs/changelog.json
  package.json
  src/config.js
  src/lib/Server.js
  src/lib/WireGuard.js
  src/package-lock.json
  src/package.json
  src/wgpw.mjs
  src/wgpw.sh
  src/www/css/app.css
  src/www/index.html
  src/www/js/api.js
  src/www/js/app.js
  src/www/js/i18n.js
  src/www/js/vendor/apexcharts.min.js
Labels: enhancement

#1262 Update How_to_generate_an_bcrypt_hash.md
  How_to_generate_an_bcrypt_hash.md
Labels: documentation

#1270 fix(Doc): fix escaping issue for PASSWORD_HASH in docker-compose.yml
  How_to_generate_an_bcrypt_hash.md
  docker-compose.yml
Labels: documentation

#1274 add better issue template
  .github/ISSUE_TEMPLATE/01-bug-report.yml
  .github/ISSUE_TEMPLATE/02-feature-request.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#1278 Update i18n.js
  src/www/js/i18n.js
Labels: documentation

#1288 Supports displaying short links
  README.md
  docker-compose.yml
  src/config.js
  src/lib/Server.js
  src/lib/WireGuard.js
  src/package-lock.json
  src/package.json
  src/www/index.html
  src/www/js/api.js
  src/www/js/app.js
Labels: enhancement

#1276 [FEATURE PROPOSAL] Remember me
  README.md
  src/config.js
  src/lib/Server.js
  src/www/index.html
  src/www/js/api.js
  src/www/js/app.js
  src/www/js/i18n.js
Labels: enhancement

#1290 Fix sort clients
  src/lib/Server.js
  src/www/index.html
  src/www/js/app.js
Labels: bug

#1291 Russian translation
  src/www/js/i18n.js
Labels: documentation

#1296 Feat expiration date
  .editorconfig
  README.md
  docker-compose.yml
  src/config.js
  src/lib/Server.js
  src/lib/WireGuard.js
  src/package-lock.json
  src/package.json
  src/www/css/app.css
  src/www/index.html
  src/www/js/api.js
  src/www/js/app.js
  src/www/js/i18n.js
  src/www/src/css/app.css
Labels: enhancement

#1304 Fix One Time Links
  README.md
  docker-compose.yml
  src/config.js
  src/lib/Server.js
  src/lib/WireGuard.js
  src/www/index.html
  src/www/js/api.js
  src/www/js/app.js
Labels: enhancement

#1299 [Feat] Prometheus metrics
  README.md
  docker-compose.yml
  src/config.js
  src/lib/Server.js
  src/lib/WireGuard.js
  src/package-lock.json
  src/package.json
Labels: type: feature request

#1332 Fix typo in How_to_generate_an_bcrypt_hash.md
  How_to_generate_an_bcrypt_hash.md
Labels: type: documentation, status: confirmed
